config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  get 'brands/show'
  post 'notifications/create'
  get 'notifications/:id' , to: 'notifications#show'
  post 'payments/paymentdetail', to: 'payments#paymentdetail'
  #resources :categories
  #get 'admins/categories', to: 'categories#index'
  root 'pages#home'
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations',passwords: 'admins/passwords',confirmations: 'admins/confirmations' }
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations',omniauth_callbacks: "users/omniauth_callbacks"}
  authenticate :admin do
    get '/admins/homepage', to:'admins#homepage'
    # get '/admins/statistics', to:'manages#index'


    #get '/admins/statistics', to:'admins#homepage'
    scope '/admins' do
      resources :admins,except: [:show]
    end
    namespace :admins do
      put 'payments/changestatus', to: 'payments#changestatus'
      resources :payments, except: [:update]
      resources :vouchers
      resources :messages
      resources :products ,except: [:destroy]
      match 'products/set_status/:id/status=:status' => 'products#destroy', :via => [:post] ,as: :product_status
      resources :categories,except: [:destroy,:show]
      match 'categories/set_status/:id/status=:status' => 'categories#destroy', :via => [:post] ,as: :category_status
      resources :brands,except: [:destroy]
      match 'brands/set_status/:id/status=:status' => 'brands#destroy', :via => [:post] ,as: :brand_status
      resources :users,except: [:destroy,:show]
      match 'users/set_status/:id/status=:status' => 'users#destroy', :via => [:post] ,as: :user_status
      resources :news,except: [:destroy]
      match 'news/set_status/:id/status=:status' => 'news#destroy', :via => [:post] ,as: :news_status
      resources :type_of_news,except: [:destroy]
      match 'type_of_news/set_status/:id/status=:status' => 'type_of_news#destroy', :via => [:post] ,as: :type_of_news_status
      resources :manages, only: [:index]
      resources :comments
      resources :carousels,except: [:show]
      resources :districts, only: [:index]
      resources :provinces, only: [:create, :index]

      post 'comments/newcomment', to: 'comments#newcomment'
      post 'comments/returncomment', to: 'comments#returncomment'
      post 'messages/received', to: 'messages#received'
      put 'payments/cancel_payment', to: 'payments#cancel_payment'
      post 'messages/watchedmore', to: 'messages#watchedmore'
      delete 'images', to:  'products#destroyimage'
      post 'news/search_products_for_news', to: 'news#search_products_for_news'
      match 'manages/process_data' => 'manages#process_data', :via => [:get] ,as: :process_data
      post 'manages/get_file_database', to: 'manages#get_file_database'
      post 'manages/set_file_database', to: 'manages#set_file_database'
      post 'manages/download/:key', to: 'manages#download',as: :dowload_file_database
      post 'manages/delete/model=:model', to: 'manages#delete',as: :delete_status_closed
    end
  end
  #user
  root 'pages#home'
  resource :carts
  get 'contacts', to: 'contacts#new'
  get 'about', to: 'pages#about'
  #  get 'login', to: 'sessions#new'
  # get 'signup', to: 'users#new'
  devise_scope :user do
    get 'users/profile', to: 'users/registrations#show'
    get 'users/order', to: 'users/registrations#order'
    get 'users/sign_out' => 'devise/sessions#destroy'
    post 'users/change_avatar', to: 'users/registrations#change_avatar'
  end
  get 'users/signup'
  get 'errors/loi'
  resources :contacts,only: [:new,:create]
  resources :messages
  get 'show', to: 'messages#show'
  post 'messages/received', to: 'messages#received'
  # resources :categories, only: [:show]
  resources :users, except: [:destroy, :index] do
    collection do
      patch 'update_password'
    end
  end
  # resources :products, only: [ :index]
  post 'products/watched_more_related_products', to: 'products#watched_more_related_products'
  get '/search', to: 'products#search', as: 'search'
  get '/products', to: 'products#index'
  delete 'images', to:  'products#destroyimage'
  get '/cart', to: 'carts#show', as: 'cart'
  post 'add', to: 'cart_products#create'
  post 'carts/destroycart', to: 'carts#destroycart'
  post 'carts/changeqt', to: 'carts#changeqt'
  resources :payments, only: [:new, :create]
  resources :carts
  resources :cart_products
  resources :comments
  post 'comments/watchedmore', to: 'comments#watchedmore'
  post 'messages/watchedmore', to: 'messages#watchedmore'

  get '/categories/:cus/:name/:brand_name', to: 'categories#show', as: 'category'
  get 'products/:name', to: 'products#show' ,as: 'product'
  get 'news', to: 'news#index' ,as: 'news_index'
  get 'news/type=:type&&title=:title', to: 'news#show', as: 'news'
  get 'news/type=:type', to: 'news#news_category', as: 'news_category'
  get 'payments/find_district', to: 'payments#find_district'
  get 'payments/find_ward', to: 'payments#find_ward'
  get 'payments/calc_shipping_fee', to: 'payments#calc_shipping_fee'
  get 'payments/cancel_payment', to: 'payments#cancel_payment'
  post 'payments/api_webhook', to: 'payments#api_webhook' 
  get 'vouchers/validate', to:'vouchers#validate'
  post 'create', to: 'messages#create'
  mount ActionCable.server => '/cable'
end

app/models/category.rb
class Category < ApplicationRecord

  #associates
  has_many :products
  has_many :brands
  enum status: [:closed, :archived,:active]
  #validate
  validates :name, presence:true, length: {minimum: 3, maximum: 30}, uniqueness:true
  # validates :description, presence:true, length: {minimum: 3, maximum: 200}, uniqueness:true
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < BaseController
  #layout 'layouts/adminshome'
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  #include ActiveModel::AttributeMethods
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show

  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit

  end

  # POST /categories
  # POST /categories.json
  def create
    @category =Category.new(category_params)
    if @category.save
      #session[:user_id] = @categories.id
      # flash[:success] = "ssASAs, #{@categories.name}"
      redirect_to admins_categories_path()
    else
      render 'new'
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update

    if @category.update(category_params)
      flash[:success] =  'Category has been changed successfully'
      redirect_to admins_categories_path()
    else
      render 'edit'
    end

  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.update_attribute(:status, params[:status])
    update_status_model(@category.products,params[:status])
    redirect_to admins_categories_path()
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    #debugger
    params.require(:category).permit(:name, :description, :display_in_navbar)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include PagesHelper
  #layout 'layouts/adminshome'
  before_action :set_category, only: [:show]
  #include ActiveModel::AttributeMethods
  # GET /categories
  # GET /categories.json
  def show
    if params[:sort] && params[:show]
      case params[:sort]
      when "1"
        @products = @category.order(id: :desc).paginate(page: params[:page], per_page: params[:show])
      when "2"
        @products = @category.order(:price).paginate(page: params[:page], per_page: params[:show])
      when "3"
        @products = @category.order(price: :desc).paginate(page: params[:page], per_page: params[:show])
      when "4"
        @products = @category.order(:name).paginate(page: params[:page], per_page: params[:show])
      else
        @products = @category.order(name: :desc).paginate(page: params[:page], per_page: params[:show])
      end
    else
      if params[:brand_name] != " " && params[:name] != " "
        @products = @category.order(id: :desc).paginate(page: params[:page], per_page: 8)
      elsif params[:brand_name] != " "
       @products = @category.order(id: :desc).paginate(page: params[:page], per_page: 8)
      else
        @products = @category.paginate(page: params[:page], per_page: 8)
      end
    end
    respond_to do |format|
      format.html
      format.js
    end
  end
  # GET /categories/new
  # POST /categories
  # POST /categories.json
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    if Category.exists? name: params[:name]
      if params[:brand_name] != " "
        @category = Category.find_by_name(params[:name]).brands.find_by_brand_name(params[:brand_name]).products.where(status: 'active')
        @category = Category.find_by_name(params[:name]).brands.find_by_brand_name(params[:brand_name]).products.where(customer: params[:cus]).where(status: 'active') if params[:cus] != " "
      else
        @category = Category.find_by_name(params[:name]).products.where(status: 'active')
        @category = Category.find_by_name(params[:name]).products.where(customer: params[:cus]).where(status: 'active')  if params[:cus] != " "
      end
    elsif params[:name] == " " 
        @category = Brand.find_by_brand_name(params[:brand_name]).products.where(status: 'active')
    else
      redirect_to root_path
      flash[:danger] = "Category with ID = #{params[:id]} is not exist"
    end
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admins/categories/_form.html.erb
<%= form_for [:admins,@category] , class:"form-group", html: { multipart: true } do |f| %>
<p style="padding:2px">Name</p>
<%= f.text_field :name, class: 'form-control',placeholder: "Name Category",maxlength:"30",minlength:"3",required:"required"%><br>
<div class="form-actions">
  <%= f.submit 'Create', class: 'btn btn-success btn-block' %>
</div>
<% end %>

app/views/admins/categories/edit.html.erb
<div class="container">
        <h1 style="text-align:center">New Category</h1><br>
    <%= render 'form' %>
</div>

app/views/admins/categories/index.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>
  <h1>Categories</h1>
  <%= link_to 'New category', new_admins_category_path,class: "btn-lg btn btn-primary fas fa-plus-square " %>
  <div class="content-box-large">
    <div class="panel-body">
      <table class="table" id="example">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Edit</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr class="gradeU">
            <td><%= category.id %></td>
            <td><%= category.name %></td>
            <td><%= link_to '', edit_admins_category_path(category),class: "btn btn-warning fas fa-edit" %></td>
            <td>
              <div class="dropdown ">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= category.status %>
                </button>
                <div class="dropdown-menu transform-status" aria-labelledby="dropdownMenuButton">
                  <% Category.statuses.to_h.except!(category.status).each do |key,value| %>
                  <%= link_to key, admins_category_status_path(:status => key.to_s,:id => category.id.to_s), method: :post,
                  data: { confirm: "The status will be changed!"},
                  class: "dropdown-item " %>
                  <% end %>
                </div>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
        <tfoot>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Edit</th>
          <th>Status</th>
        </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>
<script type="text/javascript">
dataTable = $('#example').DataTable({
stateSave: true
})
</script>

app/views/admins/categories/new.html.erb
<div class="container">
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_categories_path %>

</div>

app/views/admins/categories/show.html.erb
<div class="container" style="max-width: 40%;font-size:16px">
        <p id="notice"><%= notice %></p>
        <div class="row">
          <div class="">
              <div class="panel panel-success" >
                  <div class="panel-heading"><strong style="font-size:20px;text-align:center;">Info Category</strong></div>
                  <div class="panel-body">
                    <strong>ID:</strong>
                    <%= @category.id %><br>
                    <strong>Name:</strong>
                    <%= @category.name %><br>
                    <strong>Description:</strong>
                    <%= @category.description %><br>
                    <strong>Display in navbar:</strong>
                    <%= @category.display_in_navbar %><br>
                    <strong>Create at:</strong>
                    <%= @category.created_at %><br>
                    <strong>Update at:</strong>
                    <%= @category.updated_at %><br>
                  </div>
                </div>
          </div>
        </div>
        <%= link_to 'Edit', edit_admins_category_path(@category) %> |
        <%= link_to 'Back', admins_categories_path %>
      </div>