config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  get 'brands/show'
  post 'notifications/create'
  get 'notifications/:id' , to: 'notifications#show'
  post 'payments/paymentdetail', to: 'payments#paymentdetail'
  #resources :categories
  #get 'admins/categories', to: 'categories#index'
  root 'pages#home'
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations',passwords: 'admins/passwords',confirmations: 'admins/confirmations' }
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations',omniauth_callbacks: "users/omniauth_callbacks"}
  authenticate :admin do
    get '/admins/homepage', to:'admins#homepage'
    # get '/admins/statistics', to:'manages#index'


    #get '/admins/statistics', to:'admins#homepage'
    scope '/admins' do
      resources :admins,except: [:show]
    end
    namespace :admins do
      put 'payments/changestatus', to: 'payments#changestatus'
      resources :payments, except: [:update]
      resources :vouchers
      resources :messages
      resources :products ,except: [:destroy]
      match 'products/set_status/:id/status=:status' => 'products#destroy', :via => [:post] ,as: :product_status
      resources :categories,except: [:destroy,:show]
      match 'categories/set_status/:id/status=:status' => 'categories#destroy', :via => [:post] ,as: :category_status
      resources :brands,except: [:destroy]
      match 'brands/set_status/:id/status=:status' => 'brands#destroy', :via => [:post] ,as: :brand_status
      resources :users,except: [:destroy,:show]
      match 'users/set_status/:id/status=:status' => 'users#destroy', :via => [:post] ,as: :user_status
      resources :news,except: [:destroy]
      match 'news/set_status/:id/status=:status' => 'news#destroy', :via => [:post] ,as: :news_status
      resources :type_of_news,except: [:destroy]
      match 'type_of_news/set_status/:id/status=:status' => 'type_of_news#destroy', :via => [:post] ,as: :type_of_news_status
      resources :manages, only: [:index]
      resources :comments
      resources :carousels,except: [:show]
      resources :districts, only: [:index]
      resources :provinces, only: [:create, :index]

      post 'comments/newcomment', to: 'comments#newcomment'
      post 'comments/returncomment', to: 'comments#returncomment'
      post 'messages/received', to: 'messages#received'
      put 'payments/cancel_payment', to: 'payments#cancel_payment'
      post 'messages/watchedmore', to: 'messages#watchedmore'
      delete 'images', to:  'products#destroyimage'
      post 'news/search_products_for_news', to: 'news#search_products_for_news'
      match 'manages/process_data' => 'manages#process_data', :via => [:get] ,as: :process_data
      post 'manages/get_file_database', to: 'manages#get_file_database'
      post 'manages/set_file_database', to: 'manages#set_file_database'
      post 'manages/download/:key', to: 'manages#download',as: :dowload_file_database
      post 'manages/delete/model=:model', to: 'manages#delete',as: :delete_status_closed
    end
  end
  #user
  root 'pages#home'
  resource :carts
  get 'contacts', to: 'contacts#new'
  get 'about', to: 'pages#about'
  #  get 'login', to: 'sessions#new'
  # get 'signup', to: 'users#new'
  devise_scope :user do
    get 'users/profile', to: 'users/registrations#show'
    get 'users/order', to: 'users/registrations#order'
    get 'users/sign_out' => 'devise/sessions#destroy'
    post 'users/change_avatar', to: 'users/registrations#change_avatar'
  end
  get 'users/signup'
  get 'errors/loi'
  resources :contacts,only: [:new,:create]
  resources :messages
  get 'show', to: 'messages#show'
  post 'messages/received', to: 'messages#received'
  # resources :categories, only: [:show]
  resources :users, except: [:destroy, :index] do
    collection do
      patch 'update_password'
    end
  end
  # resources :products, only: [ :index]
  post 'products/watched_more_related_products', to: 'products#watched_more_related_products'
  get '/search', to: 'products#search', as: 'search'
  get '/products', to: 'products#index'
  delete 'images', to:  'products#destroyimage'
  get '/cart', to: 'carts#show', as: 'cart'
  post 'add', to: 'cart_products#create'
  post 'carts/destroycart', to: 'carts#destroycart'
  post 'carts/changeqt', to: 'carts#changeqt'
  resources :payments, only: [:new, :create]
  resources :carts
  resources :cart_products
  resources :comments
  post 'comments/watchedmore', to: 'comments#watchedmore'
  post 'messages/watchedmore', to: 'messages#watchedmore'

  get '/categories/:cus/:name/:brand_name', to: 'categories#show', as: 'category'
  get 'products/:name', to: 'products#show' ,as: 'product'
  get 'news', to: 'news#index' ,as: 'news_index'
  get 'news/type=:type&&title=:title', to: 'news#show', as: 'news'
  get 'news/type=:type', to: 'news#news_category', as: 'news_category'
  get 'payments/find_district', to: 'payments#find_district'
  get 'payments/find_ward', to: 'payments#find_ward'
  get 'payments/calc_shipping_fee', to: 'payments#calc_shipping_fee'
  get 'payments/cancel_payment', to: 'payments#cancel_payment'
  post 'payments/api_webhook', to: 'payments#api_webhook' 
  get 'vouchers/validate', to:'vouchers#validate'
  post 'create', to: 'messages#create'
  mount ActionCable.server => '/cable'
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end
  # GET /categories/1
  # GET /categories/1.json
  def show

  end

  # GET /categories/new
  def new
    @user1 = User.new
  end

  # GET /categories/1/edit
  def edit
  end
  #scope :created_in_time, ->(start_time, end_time){where(created_at: start_time..end_time)}
  # POST /categories
  # POST /categories.json
  def create
    # debugger
    @user1 = Admins::User.new(user_params)

    if @user1.save
      #session[:user_id] = @categories.id
      # flash[:success] = "ssASAs, #{@categories.name}"
      redirect_to admins_users_path()
    else
      render 'new'
    end
  end
  def update
    if @user1.update(user_params)
      flash[:success] =  "User #{@user1.email} password has been changed successfully"
      redirect_to admins_users_path
    else
      flash[:alert] =  'Password incorrect'
      render 'edit'
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @user1.update_attribute(:status, params[:status])
    redirect_to admins_users_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user1 = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:password,:password_confirmation)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    generic_callback("facebook")
  end

  def google_oauth2
    generic_callback( "google_oauth2" )
  end

  def generic_callback(provider)
    
    @identity = User.from_omniauth(request.env["omniauth.auth"])
    @user = @identity || current_user
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      if session[:cart] != nil
        @cart = Cart.create
        @cart.add_carts(session[:cart],current_user.id)
      end
      session[:cart] = nil
      set_flash_message(:notice, :success, kind: provider.capitalize) if is_navigational_format?
    else
      # session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_session_path, alert: "Email has already been taken, you must have another email. Please! "
    end
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
class Users::RegistrationsController < Devise::RegistrationsController
   skip_before_action :verify_authenticity_token  
   
  layout 'layouts/user'
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  before_action :authenticate_user!
  # GET /resource/sign_up
  # def new
  #  build_resource
  #   yield resource if block_given?
  #   respond_with resource
  # end
  # POST /resource
  def create
    build_resource(sign_up_params)
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        flash[:notice] = "A message with a confirmation link has been sent to your email address. Please follow the link to activate your account."
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      # resource.avatar.purge
      clean_up_passwords resource
      set_minimum_password_length
      respond_to do |format|
         format.js { render :validation_errors }
      end
  end
  SendEmailJob.set(wait: 50.seconds).perform_later(User.find_by(email: sign_up_params[:email]))
  # sign_out(current_user)
  # if sign_up_params[:avatar] == nil
  #    flash[:notice] = 'choose image for avatar'
  #    redirect_to new_user_registration_path
  #    return
  # end
  # build_resource(sign_up_params)
  # super
  # resource.save
  # yield resource if block_given?
  # if resource.persisted?
  #   if resource.active_for_authentication?
  #     set_flash_message! :notice, :signed_up
  #     sign_up(resource_name, resource)
  #     respond_with resource, location: after_sign_up_path_for(resource)
  #   else
  #     set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
  #     expire_data_after_sign_in!
  #     respond_with resource, location: after_inactive_sign_up_path_for(resource)
  #   end
  # else
  #   clean_up_passwords resource
  #   set_minimum_password_length
  #   respond_with resource
  # end
end
# GET /resource/edit
def edit
  # build_resource(current_user)
  # yield resource if block_given?
  self.resource = User.find(current_user.id)
  # respond_with self.resource
end
def show
  @user = current_user
  @payments = Payment.all.where("user_id = ?",current_user.id).order("id DESC").paginate(page: params[:page], per_page: 2)
end
def order
  @user = current_user
  if params[:status]
    case params[:status]
    when "0"
      @payments = @user.payments.where("status = 0").order("id DESC").paginate(page: params[:page], per_page: 2)
    when "1"
      @payments = @user.payments.where("status = 1").order("id DESC").paginate(page: params[:page], per_page: 2)
    when "2"
      @payments = @user.payments.where("status = 2").order("id DESC").paginate(page: params[:page], per_page: 2)
    else
      @payments = @user.payments.where("status = 3").order("id DESC").paginate(page: params[:page], per_page: 2)
    end
  else
    @payments = @user.payments.where("status = 0").order("id DESC").paginate(page: params[:page], per_page: 2)
  end
  respond_to do |format|
    format.html
    format.js
  end
end
def change_avatar
  if params[:avatar] != nil
    user = User.find(params[:user_id].to_i)
    user.avatar.purge
    user.avatar.attach(User.resize_avatar(params[:avatar]))
    redirect_to users_profile_path ,notice: "Change the avatar successfully!!!"
  else
    redirect_to users_profile_path
  end
end
# PUT /resource
def update
  @user = current_user
  if @user.update(configure_account_update_params)
    flash[:success] = "Update was saved"
    render 'show'
  else
    flash[:danger] = "Update was not saved"
    render 'show'
  end
end
# DELETE /resource
# def destroy
#   super
# end
# GET /resource/cancel
# Forces the session data which is usually expired after sign
# in to be expired now. This is useful if the user wants to
# cancel oauth signing in/up in the middle of the process,
# removing all OAuth session data.
# def cancel
#   super
# end
# protected
# If you have extra params to permit, append them to the sanitizer.
# def configure_sign_up_params
#   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
# end
# If you have extra params to permit, append them to the sanitizer.
def configure_account_update_params
  # devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  params.require(:user).permit(:firstname,:lastname ,:email, :gender, :phone,:address)
end
# The path used after sign up.
# def after_sign_up_path_for(resource)
#   super(resource)
# end
def sign_up_params
  if params[:user][:avatar] != nil
    params[:user][:avatar] =  User.resize_avatar(params[:user][:avatar])
  else
    path = "#{Rails.root}/app/assets/images/member.jpg"
    params[:user][:avatar] = Rack::Test::UploadedFile.new(path)
  end
  params.require(:user).permit(:firstname,:lastname ,:gender,:email,:password,:phone,:address,:avatar,:password_confirmation)
end
# The path used after sign up for inactive accounts.
def after_inactive_sign_up_path_for(resource)
  super(resource)
end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'layouts/user'
  # before_action :configure_sign_in_params, only: [:create]

  #include Accessible
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    if params[:user][:email].blank? || User.all.find_by_email(params[:user][:email]) == nil
      self.resource = resource_class.new(sign_in_params)
      clean_up_passwords(resource)
            flash[:alert] = "Check your email and password again"
      yield resource if block_given?
      render 'new'
    elsif User.find_by(email: params[:user][:email]).confirmed? == false
      self.resource = resource_class.new(sign_in_params)
      clean_up_passwords(resource)
      yield resource if block_given?
      render 'new'
    else
      super
      if session[:cart] != nil
        @cart = Cart.create
        @cart.add_carts(session[:cart],current_user.id)
      end
      session[:cart] = nil
      # SendEmailJob.set(wait: 50.seconds).perform_later(current_user)

    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/vouchers_controller.rb
class CouponsController < ApplicationController
  def validate
    voucher = Voucher.all.find_by(code: params[:code])
    if voucher.present?
      response = { valid: voucher.is_valid?, 
                   discounted_price: voucher.discounted_price(params[:price]) }
    else
      response = { valid: false, discounted_price: params[:price] }
    end
    respond_to do |format|
      format.json { render json: response }
    end
  end

end

app/views/admins/users/_form.html.erb
<div class="container">
  <h1 style="text-align:center">Create User With Admin</h1><br>
  <%= form_tag  admins_users_path, class:"form-group" do |f| %>
    <div>
      <div ><%= text_field_tag :email, nil, class: 'form-control',type:"email", pattern:"[a-zA-Z0-9!#$%&amp;'*+\/=?^_`{|}~.-]+@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*",placeholder: "Email" %></div><br>
      <%= text_field_tag :password, nil, class: 'form-control', type: 'password',placeholder: "Password" %>
    </div>
    <br><br>
    <div class="form-actions">
      <%= submit_tag 'Create', class: 'btn btn-success btn-block' %>
    </div>
  <% end %>
  <%= link_to 'Back', admins_users_path %>
</div>

app/views/admins/users/_formuser.html.erb
<%= render 'layouts/adminshome' %>
<div class="container">
  <%= render 'layouts/adminshome' %>
  <%= form_for  @user do |f| %>
    <div>
      <%= f.text_field :email %>
      <%= f.text_field :password %>
    </div>
  
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
  <%= link_to 'Back', admins_users_path %>
</div>

app/views/admins/users/edit.html.erb
<div class="container">
    <h1 style="text-align:center">Edit User With Admin</h1><br>
  <%= form_for @user1,  :url => url_for(:controller => 'admins/users', :action => 'update') do |f| %>
 
  <div class="form-inputs">
    <%= f.text_field :email,disabled: true, class: 'form-control' %><br>
    <%= f.text_field :password, class: 'form-control', type: 'password',placeholder: "Password" %>
     <%= f.text_field :password_confirmation, class: 'form-control', type: 'password',placeholder: "password confirmation" %>
  </div>
  <br><br>
  <div class="form-actions">
    <%= submit_tag 'Update', class: 'btn btn-success btn-block' %>
  </div>
  <% end %>
  <%= link_to 'Show', admins_user_path %> |
  <%= link_to 'Back', admins_users_path %>
</div>

app/views/admins/users/edituser.html.erb
<%= render 'layouts/adminshome' %>
<div class="container">
  <%= form_for [:admins, @user] do |f| %>
 
  <div class="form-inputs">
    <%= f.text_field :email,disabled: true %>
    <%= f.text_field :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  <% end %>
  <%= link_to 'Show', @users %> |
  <%= link_to 'Back', admins_user_path %>
</div>

app/views/admins/users/index.html.erb
<div class="container-fluid" >  <p id="notice"><%= notice %></p>
  <h1>Users</h1>
<div class="content-box-large"  >
  <div class="panel-body">
    <table id="example" class="display" width="100%">
      <thead>
        <tr>
          <th>ID</th>
          <th>Email</th>
          <th>Create At</th>
          <th>Update At</th>
          <th>Edit</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr class="gradeC">
          <td><%= user.id %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at.localtime.strftime("%d/%m/%Y %T") %></td>
          <td><%= user.updated_at.localtime.strftime("%d/%m/%Y %T") %></td>
          <td><%= link_to '', edit_admins_user_path(user),class: "btn btn-warning fas fa-edit" %></td>
          <td>
              <div class="dropdown ">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= user.status %>
                </button>
                <div class="dropdown-menu transform-status" aria-labelledby="dropdownMenuButton">
                  <% Category.statuses.to_h.except!(user.status).each do |key,value| %>
                  <%= link_to key, admins_user_status_path(:status => key.to_s,:id => user.id.to_s), method: :post,
                  data: { confirm: "The status will be changed!"},
                  class: "dropdown-item " %>
                  <% end %>
                </div>
              </div>
          </td>
        </tr>
        <% end %>
      
      </tbody>
     
    </table>
  </div>
</div>
<script type="text/javascript">
dataTable = $('#example').DataTable({
stateSave: true
})
</script>

app/views/admins/users/indexuser.html.erb
<%= render 'layouts/adminshome' %>
<div class="container-fluid">
  <p id="notice"><%= notice %></p>
  <h1>Users</h1>
  <%= link_to ' Create', new_admins_user_path, class: "btn-lg btn btn-primary fas fa-plus-square "%>
  <br>
</div>
<div class="content-box-large">
  <div class="panel-body">
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="myTable2">
      <thead>
        <tr>
          <th onclick="sortTable(0)">ID</th>
          <th onclick="sortTable(1)">Email</th>
          <th onclick="sortTable(2)">Admin?</th>
          <th onclick="sortTable(3)">Create At</th>
          <th onclick="sortTable(4)">Update At</th>
          <th>Edit</th>
          <th>Show</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |admin| %>
        <tr class="gradeU">
          <td><%= admin.id %></td>
          <td><%= admin.email %></td>
          <td><%= admin.admin %></td>
          <td><%= admin.created_at %></td>
          <td><%= admin.updated_at %></td>
          <td><%= link_to '', admin,class: "btn btn-info fas fa-eye" %></td>
          <td><%= link_to '', edit_admins_user_path(admin),class: "btn btn-warning fas fa-edit" %></td>
          <td>
            <%= link_to '', admin, method: :delete,class: "btn btn-danger far fa-trash-alt", data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
        <% end %>
        <script>
          function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("myTable2");
            switching = true;
            // Set the sorting direction to ascending:
            dir = "asc"; 
            /* Make a loop that will continue until
            no switching has been done: */
            while (switching) {
              // Start by saying: no switching is done:
              switching = false;
              rows = table.rows;
              /* Loop through all table rows (except the
              first, which contains table headers): */
              for (i = 1; i < (rows.length - 1); i++) {
                // Start by saying there should be no switching:
                shouldSwitch = false;
                /* Get the two elements you want to compare,
                one from current row and one from the next: */
                x = rows[i].getElementsByTagName("TD")[n];
                y = rows[i + 1].getElementsByTagName("TD")[n];
                /* Check if the two rows should switch place,
                based on the direction, asc or desc: */
                if (dir == "asc") {
                  if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                    // If so, mark as a switch and break the loop:
                    shouldSwitch = true;
                    break;
                  }
                } else if (dir == "desc") {
                  if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                    // If so, mark as a switch and break the loop:
                    shouldSwitch = true;
                    break;
                  }
                }
              }
              if (shouldSwitch) {
                /* If a switch has been marked, make the switch
                and mark that a switch has been done: */
                rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                switching = true;
                // Each time a switch is done, increase this count by 1:
                switchcount ++; 
              } else {
                /* If no switching has been done AND the direction is "asc",
                set the direction to "desc" and run the while loop again. */
                if (switchcount == 0 && dir == "asc") {
                  dir = "desc";
                  switching = true;
                }
              }
            }
          }
          </script>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/users/new.html.erb
<%= render 'form',user2: @user1 %>

app/views/admins/users/newuser.html.erb
<%= render 'formuser' %>

app/views/admins/users/show.html.erb
<div class="container" style="max-width: 40%;font-size:16px">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="" style="text-align:center;">
        <div class="panel panel-success" >
            <div class="panel-heading"><strong style="font-size:20px">Info User</strong></div>
            <div class="panel-body">
              <strong>ID:</strong>
              <%= @user1.id %><br>
              <strong>Email:</strong>
              <%= @user1.email %><br>
              <strong>Create at:</strong>
              <%= @user1.created_at %><br>
              <strong>Update at:</strong>
              <%= @user1.updated_at %><br>
            </div>
          </div>
    </div>
  </div>
  <%= link_to 'Edit', edit_admins_user_path() %> |
  <%= link_to 'Back', admins_users_path %>
</div>

app/views/admins/users/showuser.html.erb
<%= render 'layouts/adminshome' %>

<div class="container" style="max-width: 40%;font-size:16px">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="" style="text-align:center;">
        <div class="panel panel-success" >
            <div class="panel-heading"><strong style="font-size:20px">Info User</strong></div>
            <div class="panel-body">
              <strong>ID:</strong>
              <%= @users.id %><br>
              <strong>Email:</strong>
              <%= @users.email %><br>
              <strong>Create at:</strong>
              <%= @users.created_at %><br>
              <strong>Update at:</strong>
              <%= @users.updated_at %><br>
            </div>
          </div>
    </div>
  </div>
  <%= link_to 'Edit', edit_admins_user_path(@users) %> |
  <%= link_to 'Back', admins_user_path %>
</div>