config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  get 'brands/show'
  post 'notifications/create'
  get 'notifications/:id' , to: 'notifications#show'
  post 'payments/paymentdetail', to: 'payments#paymentdetail'
  #resources :categories
  #get 'admins/categories', to: 'categories#index'
  root 'pages#home'
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations',passwords: 'admins/passwords',confirmations: 'admins/confirmations' }
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations',omniauth_callbacks: "users/omniauth_callbacks"}
  authenticate :admin do
    get '/admins/homepage', to:'admins#homepage'
    # get '/admins/statistics', to:'manages#index'


    #get '/admins/statistics', to:'admins#homepage'
    scope '/admins' do
      resources :admins,except: [:show]
    end
    namespace :admins do
      put 'payments/changestatus', to: 'payments#changestatus'
      resources :payments, except: [:update]
      resources :vouchers
      resources :messages
      resources :products ,except: [:destroy]
      match 'products/set_status/:id/status=:status' => 'products#destroy', :via => [:post] ,as: :product_status
      resources :categories,except: [:destroy,:show]
      match 'categories/set_status/:id/status=:status' => 'categories#destroy', :via => [:post] ,as: :category_status
      resources :brands,except: [:destroy]
      match 'brands/set_status/:id/status=:status' => 'brands#destroy', :via => [:post] ,as: :brand_status
      resources :users,except: [:destroy,:show]
      match 'users/set_status/:id/status=:status' => 'users#destroy', :via => [:post] ,as: :user_status
      resources :news,except: [:destroy]
      match 'news/set_status/:id/status=:status' => 'news#destroy', :via => [:post] ,as: :news_status
      resources :type_of_news,except: [:destroy]
      match 'type_of_news/set_status/:id/status=:status' => 'type_of_news#destroy', :via => [:post] ,as: :type_of_news_status
      resources :manages, only: [:index]
      resources :comments
      resources :carousels,except: [:show]
      resources :districts, only: [:index]
      resources :provinces, only: [:create, :index]

      post 'comments/newcomment', to: 'comments#newcomment'
      post 'comments/returncomment', to: 'comments#returncomment'
      post 'messages/received', to: 'messages#received'
      put 'payments/cancel_payment', to: 'payments#cancel_payment'
      post 'messages/watchedmore', to: 'messages#watchedmore'
      delete 'images', to:  'products#destroyimage'
      post 'news/search_products_for_news', to: 'news#search_products_for_news'
      match 'manages/process_data' => 'manages#process_data', :via => [:get] ,as: :process_data
      post 'manages/get_file_database', to: 'manages#get_file_database'
      post 'manages/set_file_database', to: 'manages#set_file_database'
      post 'manages/download/:key', to: 'manages#download',as: :dowload_file_database
      post 'manages/delete/model=:model', to: 'manages#delete',as: :delete_status_closed
    end
  end
  #user
  root 'pages#home'
  resource :carts
  get 'contacts', to: 'contacts#new'
  get 'about', to: 'pages#about'
  #  get 'login', to: 'sessions#new'
  # get 'signup', to: 'users#new'
  devise_scope :user do
    get 'users/profile', to: 'users/registrations#show'
    get 'users/order', to: 'users/registrations#order'
    get 'users/sign_out' => 'devise/sessions#destroy'
    post 'users/change_avatar', to: 'users/registrations#change_avatar'
  end
  get 'users/signup'
  get 'errors/loi'
  resources :contacts,only: [:new,:create]
  resources :messages
  get 'show', to: 'messages#show'
  post 'messages/received', to: 'messages#received'
  # resources :categories, only: [:show]
  resources :users, except: [:destroy, :index] do
    collection do
      patch 'update_password'
    end
  end
  # resources :products, only: [ :index]
  post 'products/watched_more_related_products', to: 'products#watched_more_related_products'
  get '/search', to: 'products#search', as: 'search'
  get '/products', to: 'products#index'
  delete 'images', to:  'products#destroyimage'
  get '/cart', to: 'carts#show', as: 'cart'
  post 'add', to: 'cart_products#create'
  post 'carts/destroycart', to: 'carts#destroycart'
  post 'carts/changeqt', to: 'carts#changeqt'
  resources :payments, only: [:new, :create]
  resources :carts
  resources :cart_products
  resources :comments
  post 'comments/watchedmore', to: 'comments#watchedmore'
  post 'messages/watchedmore', to: 'messages#watchedmore'

  get '/categories/:cus/:name/:brand_name', to: 'categories#show', as: 'category'
  get 'products/:name', to: 'products#show' ,as: 'product'
  get 'news', to: 'news#index' ,as: 'news_index'
  get 'news/type=:type&&title=:title', to: 'news#show', as: 'news'
  get 'news/type=:type', to: 'news#news_category', as: 'news_category'
  get 'payments/find_district', to: 'payments#find_district'
  get 'payments/find_ward', to: 'payments#find_ward'
  get 'payments/calc_shipping_fee', to: 'payments#calc_shipping_fee'
  get 'payments/cancel_payment', to: 'payments#cancel_payment'
  post 'payments/api_webhook', to: 'payments#api_webhook' 
  get 'vouchers/validate', to:'vouchers#validate'
  post 'create', to: 'messages#create'
  mount ActionCable.server => '/cable'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :user

    def total_price
      cart_products.to_a.sum { |item| item.price}
    end
	# def add_product(product_params)
 #    current_item = cart_products.find_by(product_id: product_params[:product][:product_id])
 #    if current_item
 #      current_item.quantity += product_params[:product][:quantity].to_i
 #    current_item.save
 #    else
 #    new_item = cart_products.create(product_id: product_params[:product][:product_id],
 #      quantity: product_params[:product][:quantity],
 #      cart_id: self.id)
 #    end
 #    new_item
 #  end
  
  def add_carts(carts,user_id)
    @checkcarts = Cart.where(user_id: user_id)
    if @checkcarts != nil || @checkcarts.count > 0
       i = 0 
       while i < carts.count do
          @checkcarts.map do |item|
            if (carts[i]['product_id'].to_i == item.product_id) && (carts[i]['size'].to_i != item.size)   
                  new_item = Cart.new
                  new_item.user = User.find(user_id)
                  new_item.product_id = carts[i]['product_id'].to_i
                  new_item.price = carts[i]['price'].to_f
                  new_item.size = carts[i]['size'].to_i
                  new_item.quantity = carts[i]['quantity'].to_i
                  new_item.save
            end
            if (carts[i]['product_id'].to_i == item.product_id) && (carts[i]['size'].to_i == item.size) 
                  @cart = Cart.find(item.id)
                  @cart.quantity = @cart.quantity + carts[i]['quantity'].to_i
                  @cart.save 
            end  
          end
          @checkpresent = Cart.where(user_id: user_id).where(product_id: carts[i]['product_id'].to_i).where(size: carts[i]['size'].to_i)   
          if @checkpresent.count == 0
                new_item = Cart.new
                new_item.user = User.find(user_id)
                new_item.product_id = carts[i]['product_id'].to_i
                new_item.price = carts[i]['price'].to_f
                new_item.size = carts[i]['size'].to_i
                new_item.quantity = carts[i]['quantity'].to_i
                new_item.save
          end
        i = i + 1
      end
    else
       i = 0 
       while i < carts.count do
          new_item = Cart.new
          new_item.user = User.find(user_id)
          new_item.product_id = carts[i]['product_id'].to_i
          new_item.price = carts[i]['price'].to_f
          new_item.size = carts[i]['size'].to_i
          new_item.quantity = carts[i]['quantity'].to_i
          new_item.save
       end
    end

end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :verify_authenticity_token
  include CartProductsHelper
  before_action :check_cart, only: [:show]
  before_action :check_quanity, only: [:create]
  def changeqt
    @checkqt = 0
    @resetvalue = 0
    if user_signed_in? == true
      @cartss = Cart.where(user_id: current_user.id).where(product_id: params[:item][:id]).where(size: params[:item][:size])
      if Product.find(@cartss.first.product_id).stocks.find_by(size: params[:item][:size]) == nil
        @checkqt = 2
        @cartss.first.destroy
      elsif (Product.find(@cartss.first.product_id).stocks.find_by(size: params[:item][:size]).quantity.to_i < params[:item][:qt].to_i)
        @checkqt = 1
        @resetvalue = Product.find(@cartss.first.product_id).stocks.find_by(size: params[:item][:size]).quantity.to_i
      else
        @cartss.first.quantity = params[:item][:qt]
        @cartss.first.save
      end
    else
      @cartss = get_carts
      i = 0
      while i < @cartss.count do
          if @cartss[i]['product_id'] == params[:item][:id] && @cartss[i]['size'] == params[:item][:size]
            if Product.find(@cartss[i]['product_id']).stocks.find_by(size: params[:item][:size]) == nil
              @checkqt = 2
              @cartss.delete_at(i)
            elsif (Product.find(@cartss[i]['product_id']).stocks.find_by(size: params[:item][:size]).quantity.to_i < params[:item][:qt].to_i)
              @checkqt = 1
              @resetvalue = Product.find(@cartss[i]['product_id']).stocks.find_by(size: params[:item][:size]).quantity.to_i
            else
              @cartss[i]['quantity'] = params[:item][:qt]
            end
          end
          i = i + 1
        end
        @cartss = nil if @cartss.count == 0
        session[:cart] = @cartss
      end

    end

    def destroycart
      @location = nil
      if user_signed_in?
        @location = Cart.where(user_id: current_user.id).where(product_id: params[:item][:id]).where(size: params[:item][:size]).first.destroy
        if Cart.where(user_id: current_user.id).count == 0
          redirect_to root_path
        end
      else
        @cartss = session[:cart]
        i = 0
        while i < @cartss.count do
            if @cartss[i]['product_id'] == params[:item][:id] && @cartss[i]['size'] == params[:item][:size]
              @location = @cartss.delete_at(i)
              break
            end
            i = i + 1
          end
          if @cartss.count == 0
            session[:cart] = nil
            redirect_to root_path
          else
            session[:cart] = @cartss
          end
        end
      end
      def show
        # @cart = current_cart
      end
      def create
        if user_signed_in?
          @checkcarts = Cart.where(user_id: current_user.id)
          @checkpresent = Cart.where(user_id: current_user.id).where(product_id: params[:product_id]).where(size: params[:addcart][:size])
          if @checkcarts != nil && @checkcarts.count != 0
            @checkcarts.each do |item|
              if (item.product_id == params[:product_id].to_i) && (item.size != params[:addcart][:size].to_i)
                @cart = Cart.new
                @cart.product_id = Product.find(params[:product_id]).id
                @cart.size = params[:addcart][:size]
                @cart.quantity = params[:addcart][:quantity]
                @cart.price =  Product.find(params[:product_id]).price
                @cart.user = current_user
                @cart.save
              end
              if (item.product_id == params[:product_id].to_i) && (item.size == params[:addcart][:size].to_i)
                @cart = Cart.find(item.id)
                @cart.quantity = @cart.quantity + params[:addcart][:quantity].to_i
                @cart.save
              end
            end
          else
            @cart = Cart.new
            @cart.product_id = Product.find(params[:product_id]).id
            @cart.size = params[:addcart][:size]
            @cart.quantity = params[:addcart][:quantity]
            @cart.price =  Product.find(params[:product_id]).price
            @cart.user = current_user
            @cart.save
          end
          if @checkpresent.count == 0
            @cart = Cart.new
            @cart.product_id = Product.find(params[:product_id]).id
            @cart.size = params[:addcart][:size]
            @cart.quantity = params[:addcart][:quantity]
            @cart.price =  Product.find(params[:product_id]).price
            @cart.user = current_user
            @cart.save
          end

        else
          # debugger
          carts = session[:cart]
          if carts != nil
            update = carts.find {|x| x['product_id'] == params[:product_id] && x['size'] == params[:addcart][:size] }
            if update != nil
              carts.map do |item|
                if item['product_id'] == params[:product_id] &&  item['size'] == params[:addcart][:size]
                  item['quantity'] = params[:addcart][:quantity].to_i + update['quantity'].to_i
                end
              end
            else
              cartsnew = {
                "product_id" => params[:product_id],
                "price" =>  Product.find(params[:product_id]).price,
                "size"  => params[:addcart][:size] ,
                "quantity"  => params[:addcart][:quantity]
              }
              carts.push(cartsnew)
            end
          else
            carts = []
            carts.push({
                         "product_id" => params[:product_id],
                         "price" =>  Product.find(params[:product_id]).price,
                         "size"  => params[:addcart][:size] ,
                         "quantity"  => params[:addcart][:quantity]
            })
          end
          session[:cart] = carts

          respond_to do |format|
            format.html
            format.js
          end
        end
      end
      private

      def check_cart
        @carts = 0
        @total = 0
        if user_signed_in?
          checkallquantity_cart_user(current_user.id)
          @carts = Cart.where(user_id: current_user.id)
          if @carts.count == 0
            redirect_to root_path
          else
            @carts.each do |item|
              @total = @total + (item["price"].to_i*item["quantity"].to_i)
            end
          end
        else
          if session[:cart] != nil
            @carts = checkallquantity_cart_session(session[:cart])
            redirect_to root_path  if @carts.count == 0
            i = 0
            while i < @carts.count do
                @total = @total + (@carts[i]["price"].to_i*@carts[i]["quantity"].to_i)
                i = i + 1
              end
              else
                redirect_to root_path
              end
            end
          end
        end
     

     def check_quanity
        @check = Product.find(params[:product_id]).stocks.find_by_size(params[:addcart][:size])
        if @check.quantity < params[:addcart][:quantity].to_i
          flash[:danger] = "Product was out of stocks"
          render 'show' 
          return
        end
    end

app/views/carts/changeqt.js.erb
if ("<%= @checkqt %>" == '1') {
    $('input[name=item' + "<%= params[:item][:id] %>" + "<%= params[:item][:size] %>" + ']').val("<%= @resetvalue %>");
    $.alert({
        title: 'Notification',
        content: 'Only still <%= @resetvalue %> quantity in warehouse',
        animation: 'scale',
        closeAnimation: 'bottom',
        backgroundDismiss: true,
        buttons: {
            okay: {
                text: 'okay',
                btnClass: 'btn-blue',
                action: function() {
                    location.reload();
                }
            }
        }
    });
}
if ("<%= @checkqt %>" == '2') {
    $.alert({
        title: 'Notification',
        content: 'Sorry! Out of stock',
        animation: 'scale',
        closeAnimation: 'bottom',
        backgroundDismiss: true,
        buttons: {
            okay: {
                text: 'okay',
                btnClass: 'btn-blue',
                action: function() {
                    location.reload();
                }
            }
        }
    });
}
if ("<%= @checkqt %>" == '0') {
    $.confirm({
        title: 'Notification',
        content: 'Update quantity item cart, success!!!',
        autoClose: 'Wait|500',
        buttons: {
            Wait: {
                action: function() {
                    location.reload();
                }
            }
        }
    });
}

app/views/carts/create.js.erb
$(".cart-text ").text('<%= user_signed_in? == false ? session[:cart].sum { |h| h["quantity"].to_i} : Cart.where(user_id: current_user.id).sum { |h| h[:quantity].to_i}  %>' );
$.alert({
    title: 'Notification',
    content: 'Add an item to cart, Susscess!!!',
});

app/views/carts/destroycart.js.erb
$.alert({
    title: 'Notification',
    content: 'Product in the cart has been deleted!',
});
var total = parseInt("<%= @location['price'].to_i*@location['quantity'].to_i %>");
var update = parseInt($('#total_carts').text().replace('TOTAL:', '').replace(',', '').replace(',', '').replace('$', '')) - total;
$('#total_carts').text('TOTAL: ' + update + ' VND');

app/views/carts/show.html.erb
<div class="cart">
  <div class="container">
    <div class="row mt-5">
      <div class="col-lg-9 col-md-6">
        <h3>Your Shopping Bag(<%= @carts.count %>)</h3>
        <% @carts.each do |item| %>
        <div id=item<%= item["product_id"]%><%= item["size"]%> class="cart-item-list border-top pt-4">
          <div class="row cart-item m-0">
            <div class="col-lg-2 p-0">
              <%=image_tag Product.find(item["product_id"]).images.first, style:"width:100%; height:150px" %>
            </div>
            <div class="col-lg-4">
              <h5><strong><%= Product.find(item["product_id"]).name %> </strong></h5>
              <p class="badge badge-primary"><%= Product.find(item["product_id"]).brand.brand_name %></p>
              <p><span>Description: <%= truncate(Product.find(item["product_id"]).description, :length => 50)  %></span></p>
              <p >Size: <%= item["size"] %></p>
            </div>
            <div class="col-lg-1 p-0">
              <!-- <p>Qty: </p> -->
              <input min="1" id="changecart" onchange="checkqt(<%= item["product_id"]%>,<%= item["size"]%>,this.value);" type="number" name=item<%= item["product_id"]%><%= item["size"]%> value=<%= item["quantity"] %>  >
            </div>
            <div class="col-lg-2">
              <p>Price: <%= number_to_currency( item["price"], unit: "VNĐ", separator: ",",precision: 0, format: "%n %u")%></p>
            </div>
            <div class="col-lg-2 p-0">
              <p>SubTotal: <%= number_to_currency(item["price"].to_i*item["quantity"].to_i, unit: "VNĐ", separator: ",",precision: 0, format: "%n %u" ) %></p>
            </div>
            <div class="col-lg-1 p-0">
              <!--     link_to '<i class="fas fa-minus"></i>'.html_safe, destroycart_path(item), method: :delete, data: { confirm: "Delete this order?"} %>
              <a href="#" class="btn btn-danger">
              <i class="fas fa-times"></i></a> -->
              <input id=btn<%= item["id"] %> class="btn btn-danger media-btn-close-cart" onclick="deleteitemcart(<%= item["product_id"]%>,<%= item["size"]%>);" type="button" value="x" >
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <div class="col-lg-3 col-md-6 border-left">
        <h3>ORDER SUMMARY</h3>
        <!--         <p class="pt-4 border-top">Total:  @total %>$</p>
        -->        <h4 id="total_carts" class="border-top">TOTAL:
        <%= number_to_currency(@total, unit: "VNĐ", separator: ",",precision: 0, format: "%n %u") %> </h4>
        <%= link_to "PROCEED TO CHECKOUT",new_payment_path(), class: "btn btn-dark w-100" %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$('#changecart').on('input', function() {
  this.value = this.value.replace(/[^\d]/g, '');
  if(this.value == "" || this.value == 0){
  this.value= 1;
  }
});

function deleteitemcart(id, s) {
  if (confirm("Are your sure to delete this item from cart?")) {
    $("#item" + id + s).fadeOut('1000', function(c) {
      $("#item" + id + s).remove();
      });
    $.ajax({
      url: "/carts/destroycart",
      type: "post",
      dataType: "script",
      data: {
        item: {
        "id": id,
        "size": s
        }
      }
    });
}
}
function checkqt(id, s, qt) {
if (parseInt(qt) < 1 || parseInt(qt) == 0) {
$('input[name=item' + id + "" + s + ']').val(1);
}
$.ajax({
url: "/carts/changeqt",
type: "post",
dataType: "script",
data: {
item: {
"id": id,
"size": s,
"qt": qt
}
}
});
}
</script>