config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  get 'brands/show'
  post 'notifications/create'
  get 'notifications/:id' , to: 'notifications#show'
  post 'payments/paymentdetail', to: 'payments#paymentdetail'
  #resources :categories
  #get 'admins/categories', to: 'categories#index'
  root 'pages#home'
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations',passwords: 'admins/passwords',confirmations: 'admins/confirmations' }
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations',omniauth_callbacks: "users/omniauth_callbacks"}
  authenticate :admin do
    get '/admins/homepage', to:'admins#homepage'
    # get '/admins/statistics', to:'manages#index'


    #get '/admins/statistics', to:'admins#homepage'
    scope '/admins' do
      resources :admins,except: [:show]
    end
    namespace :admins do
      put 'payments/changestatus', to: 'payments#changestatus'
      resources :payments, except: [:update]
      resources :vouchers
      resources :messages
      resources :products ,except: [:destroy]
      match 'products/set_status/:id/status=:status' => 'products#destroy', :via => [:post] ,as: :product_status
      resources :categories,except: [:destroy,:show]
      match 'categories/set_status/:id/status=:status' => 'categories#destroy', :via => [:post] ,as: :category_status
      resources :brands,except: [:destroy]
      match 'brands/set_status/:id/status=:status' => 'brands#destroy', :via => [:post] ,as: :brand_status
      resources :users,except: [:destroy,:show]
      match 'users/set_status/:id/status=:status' => 'users#destroy', :via => [:post] ,as: :user_status
      resources :news,except: [:destroy]
      match 'news/set_status/:id/status=:status' => 'news#destroy', :via => [:post] ,as: :news_status
      resources :type_of_news,except: [:destroy]
      match 'type_of_news/set_status/:id/status=:status' => 'type_of_news#destroy', :via => [:post] ,as: :type_of_news_status
      resources :manages, only: [:index]
      resources :comments
      resources :carousels,except: [:show]
      resources :districts, only: [:index]
      resources :provinces, only: [:create, :index]

      post 'comments/newcomment', to: 'comments#newcomment'
      post 'comments/returncomment', to: 'comments#returncomment'
      post 'messages/received', to: 'messages#received'
      put 'payments/cancel_payment', to: 'payments#cancel_payment'
      post 'messages/watchedmore', to: 'messages#watchedmore'
      delete 'images', to:  'products#destroyimage'
      post 'news/search_products_for_news', to: 'news#search_products_for_news'
      match 'manages/process_data' => 'manages#process_data', :via => [:get] ,as: :process_data
      post 'manages/get_file_database', to: 'manages#get_file_database'
      post 'manages/set_file_database', to: 'manages#set_file_database'
      post 'manages/download/:key', to: 'manages#download',as: :dowload_file_database
      post 'manages/delete/model=:model', to: 'manages#delete',as: :delete_status_closed
    end
  end
  #user
  root 'pages#home'
  resource :carts
  get 'contacts', to: 'contacts#new'
  get 'about', to: 'pages#about'
  #  get 'login', to: 'sessions#new'
  # get 'signup', to: 'users#new'
  devise_scope :user do
    get 'users/profile', to: 'users/registrations#show'
    get 'users/order', to: 'users/registrations#order'
    get 'users/sign_out' => 'devise/sessions#destroy'
    post 'users/change_avatar', to: 'users/registrations#change_avatar'
  end
  get 'users/signup'
  get 'errors/loi'
  resources :contacts,only: [:new,:create]
  resources :messages
  get 'show', to: 'messages#show'
  post 'messages/received', to: 'messages#received'
  # resources :categories, only: [:show]
  resources :users, except: [:destroy, :index] do
    collection do
      patch 'update_password'
    end
  end
  # resources :products, only: [ :index]
  post 'products/watched_more_related_products', to: 'products#watched_more_related_products'
  get '/search', to: 'products#search', as: 'search'
  get '/products', to: 'products#index'
  delete 'images', to:  'products#destroyimage'
  get '/cart', to: 'carts#show', as: 'cart'
  post 'add', to: 'cart_products#create'
  post 'carts/destroycart', to: 'carts#destroycart'
  post 'carts/changeqt', to: 'carts#changeqt'
  resources :payments, only: [:new, :create]
  resources :carts
  resources :cart_products
  resources :comments
  post 'comments/watchedmore', to: 'comments#watchedmore'
  post 'messages/watchedmore', to: 'messages#watchedmore'

  get '/categories/:cus/:name/:brand_name', to: 'categories#show', as: 'category'
  get 'products/:name', to: 'products#show' ,as: 'product'
  get 'news', to: 'news#index' ,as: 'news_index'
  get 'news/type=:type&&title=:title', to: 'news#show', as: 'news'
  get 'news/type=:type', to: 'news#news_category', as: 'news_category'
  get 'payments/find_district', to: 'payments#find_district'
  get 'payments/find_ward', to: 'payments#find_ward'
  get 'payments/calc_shipping_fee', to: 'payments#calc_shipping_fee'
  get 'payments/cancel_payment', to: 'payments#cancel_payment'
  post 'payments/api_webhook', to: 'payments#api_webhook' 
  get 'vouchers/validate', to:'vouchers#validate'
  post 'create', to: 'messages#create'
  mount ActionCable.server => '/cable'
end

app/models/message.rb
class Message < ApplicationRecord

	belongs_to :admin
	belongs_to :user

end

app/controllers/admins/messages_controller.rb
class Admins::MessagesController < BaseController
  skip_before_action :verify_authenticity_token
  before_action :set_user_message , only: [:show]

  def watchedmore
    @messages = Message.where(user_id: params[:info][:user_id].to_i).order('created_at desc').limit(10).offset(params[:info][:offset].to_i)
  end

  def create
    # debugger
    @message = Message.new
    @message.content = params[:post][:content].gsub(/[\r\n]/, '<br />')
    @message.user = User.find(params[:user_id][:user_id])
    @message.admin = Admin.first
    @message.usersend = params[:user_send][:usersend]
    @message.save

    @list_new_message = reload_new_messages.flatten

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show

    @list_new_message = []
    @list_new_message = reload_new_messages.flatten


  end

  def index
    @list = []
    @messages = Message.order("created_at DESC").all.uniq{|e| e[:user_id] }
    @messages.each {|v|

      @list.push(User.find(v.user.id))
    }
  end

  def received
    @content = Message.where(user_id: params[:data][:message][:message][:user_id].to_i).last.content
    @list_new_message = reload_new_messages.flatten

  end

  private

  def set_user_message
    @messages = Message.all.where(user_id: params[:id]).order('created_at desc').limit(10).reverse
    @message = Message.new
  end

  def reload_new_messages
    @list_new_message = []
    @list_messages = Message.order("created_at DESC").all.uniq{|e| e[:user_id] }
    @list_messages.each {|v|
      if v.user.messages.last.usersend == true
        @list_new_message.push(User.find(v.user.id))
      end
    }
    @list_new_message
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    @message = Message.new
    @message.content = params[:message][:content].gsub(/[\r\n]/, '<br />')
    @message.user = User.find(params[:user_id][:user_id])
    @message.admin = Admin.first
    @message.usersend = params[:user_send][:usersend]
    @message.save
    respond_to do |format|
      format.html
      format.js
    end
    # debugger
    # respond_to(:js)
  end
  def show
  end
  def received
    @content = Message.where(user_id: params[:data][:message][:message][:user_id].to_i).last.content
  end
  def watchedmore
    @messages = Message.where(user_id: params[:info][:user_id].to_i).order('created_at desc').limit(10).offset(params[:info][:offset].to_i)
  end
end

app/views/admins/messages/_new_message_to_user.html.erb
<% obj.delete_if { |u| u["id"] == params[:id].to_i }.each do |user| %>
		<%= link_to admins_message_path(user),target: "_blank" do %>
		<div class="media mt-3 message_new">
			<%= image_tag user.avatar.attached? == false ? " ": user.avatar,class: "align-self-center mr-3" %>
			<div class="media-custom">
				<u><%= user.firstname %></u>
				<p class="text-danger"><%= user.messages.last.content %></p>
			</div>
		</div>
	<% end %>
<% end %>

app/views/admins/messages/create.js.erb
$(".user_message").empty();
$(".user_message").html("<%= j render 'new_message_to_user' , obj: @list_new_message.take(10) %>");
document.getElementById("adminchat").value = null;
$('#admin_chat' + "<%= @message.user_id %>").append("<li class='self'> <div class='avatar'></div> <div class='msg'> <p>" + "<%= raw @message.content %>" + "</p> <time>" + "<%= time_ago_in_words(@message.created_at) %>" + "</time> </div> </li>");
// window.scrollTo(0, 9999999999999999999999999);
var mydiv = $('#admin_chat' + "<%= @message.user_id %>");
mydiv.scrollTop(mydiv.prop("scrollHeight"));
$(document).ready(function() {
    "<% if Message.all.where('user_id=?',@message.user_id).count > 10 %>"
    $('#admin_chat' + "<%= @message.user_id %>" + ' li').first().remove();
    "<% end %>"
    var messsage = {
        "usersend": "<%= @message.usersend %>",
        "user_id": "<%= @message.user_id %>",
        "avatar": '<%= url_for(@message.user.avatar) %>',
        "name": "<%= @message.user.firstname %>",
        "time": "<%= time_ago_in_words(@message.created_at) %>",
        "content": "<%= @message.content %>"
    };
    App.message_admin.admin_send_msg(messsage);
    App.message_admin.received = function(data) {
     
    }
})

app/views/admins/messages/index.html.erb
<% @list.each do |user| %>
<div class="card-body">
	<div class="row">
		<div class="col-md-1 col-xs-12 col-sm-2 col-lg-2">
			<%= image_tag user.avatar.attached? == false ? " ": user.avatar,class: "rounded-circle img-thumbnail" %>
		</div>
		<div class="col-md-11 col-xs-12 col-sm-10 col-lg-10" >
			<div class="container" >
				<h2><%= user.firstname %></h2>
				<hr>
				<b><%= user.messages.last.content %>
                   <% if user.messages.last.usersend == true %>
                   <p class="checkmessage">Check message of user , please !!!</p>
                   <% end %>

				 </b>
				<hr>
				<div class="col-sm-5 col-xs-6 tital " >
					<%= link_to "", admins_message_path(user), class: "btn btn-lg btn-success fa fa-eye" %>
				</div>
			</div>
		</div>
	</div>
	<hr>
</div>
<% end %>

app/views/admins/messages/received.js.erb
document.body.scrollTop = document.body.scrollHeight;
$('#admin_chat'+"<%=params[:data][:message][:message]['user_id'] %>").append("<li class='other'> <div class='avatar'><img src="+"<%=params[:data][:message][:message]['avatar'] %>"+" /></div> <div class='msg'> <p>"+"<%= raw @content %>"+"</p> <time>"+"<%=params[:data][:message][:message]['time'] %>"+"</time> </div> </li>");
window.scrollTo(0, 9999999999999999999999999);
"<% if Message.all.where('user_id=?', params[:data][:message][:message]['user_id']).count > 10 %>"
$('#admin_chat'+"<%=params[:data][:message][:message]['user_id'] %> "+' li').first().remove();
"<% end %>"
 $( ".user_message" ).empty();
$(".user_message").html("<%= j render 'new_message_to_user' , obj: @list_new_message.take(10) %>");

app/views/admins/messages/show.html.erb
			<div class="menu-chat">
			<div class="back"><%= link_to raw("&#xf053"), admins_messages_path , class: "fa "  %> <%= image_tag @messages[0].user.avatar%></div>
			<div class="name"><%= @messages[0].user.firstname %></div>
			<div class="last"><%= time_ago_in_words(@messages.last.created_at) %></div>
		</div>
	<div class="row">
		<div class="col-lg-2 mt-5">
			<div class="user_message bg-light ">
				<%= render 'new_message_to_user' , obj: @list_new_message.take(10)  %>
			</div>
		</div>
		<div class="col-lg-10">
		<ol id=admin_chat<%= @messages[0].user.id %> class="chat">
			<% if Message.all.where("user_id=?", @messages[0].user.id).count > 10 %>
			<div id="btn-loadmessage" align="center" class="mt-3">
		        <button  id="loadmessage" class="btn btn-info">More</button>
		     </div>
		     <% end %>
			<% @messages.each do |v|  %>
			<% if v.usersend == true%> 
			<li class="other">                        
				<div class="avatar"><%= image_tag v.user.avatar%></div>
				<div class="msg">
					<p><%= raw v.content %></p>
					<time><%= time_ago_in_words(v.created_at) %></time>
				</div>
			</li>
			<% else %>
			<li class="self">
				<div class="avatar"></div>
				<div class="msg">
					<p><%= raw v.content %></p>
					<time><%= time_ago_in_words(v.created_at) %></time>
				</div>
			</li>
			<% end %>
			<% end %>
		</ol>
		<%= form_for([:admins,@message] ,as: :post,:remote=>true, :url => {:controller => "admins/messages", :action => "create"}, :html => {class: "textarea", role: "form" , :method => :POST}) do |f| %>
		            <%= hidden_field_tag "user_send[usersend]", "#{false}" %>
		             <%= hidden_field_tag "user_id[user_id]", "#{@messages[0].user.id}" %>
		            <%= f.text_area :content, placeholder: "Type message..", autofocus: true , class: "form-container-custom-admin",id: "adminchat" %>
		            <%= f.submit raw("&#xf1d8") , class: "btn pull-right fa text-primary right-icon-plane"  %>
		<% end %>
	</div>
	</div>
<script type="text/javascript">
	$(document).ready(function(){

    $('html, body').animate({
        scrollTop: $("#adminchat").offset().top
    }, 2000);

		})
</script>
<script type="text/javascript">
		  var count_message = 1; 
		     $( "#loadmessage" ).click(function() {
	      count_message = count_message + 5;
	      var user_id = "<%= @messages[0].user.id %>";
	       $.ajax({
	       url: "/admins/messages/watchedmore",
	       type: "post",
	       dataType: "script",
	       data: { info: { "offset": count_message,"user_id": user_id }}
	       });
	  });
</script>

app/views/admins/messages/watchedmore.js.erb
"<% @messages.each do |message| %>"
  "<% if message.usersend == true  %>"
    $( "<li class='other'> <div class='avatar'><img src=<%= url_for(message.user.avatar) %>  ></div> <div class='msg'> <p><%= raw message.content %></p> <time><%= time_ago_in_words(message.created_at) %></time> </div> </li>" ).insertAfter( "#btn-loadmessage" );
   "<% else %>"
    $( "<li class='self'> <div class='avatar'></div> <div class='msg'> <p><%= raw message.content %></p> <time><%= time_ago_in_words(message.created_at) %></time> </div> </li>" ).insertAfter( "#btn-loadmessage" );
  "<% end %>"
"<% end %>"